### ISSUE TITLE
decouple mixins from packages

### ISSUE THREAD

**Issue by avalanchesass** [avalanchesass/avalanche#70]
- should mixins be prefixed (o-, c-, u-)? -> yes

**Comment by maoberlehner** [comment]
I think best would be to name mixin packages like `avalanche_component_grid_mixin` and mixins like `o-grid`

**Comment by maoberlehner** [comment]
mixins are nore bundled with packages but in a separate file - so it is possible to load only the mixin file - so it is not necessary to have separate mixin packages
